name: Auto Update Changelog

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'CHANGELOG.md'
      - '.github/**'
      - 'dist/**'
  workflow_dispatch:

jobs:
  should-run:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - id: check
        run: |
          # Skip if commit message contains skip tags
          if echo "${{ github.event.head_commit.message }}" | grep -qiE "\[skip ci\]|\[skip changelog\]"; then
            echo "should-run=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Skip if this is a release-related commit
          if echo "${{ github.event.head_commit.message }}" | grep -qiE "^(chore|docs).*: update CHANGELOG\.md for v[0-9]+\.[0-9]+\.[0-9]+"; then
            echo "should-run=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Skip if the previous commit was a version bump
          if git log -1 --pretty=%B | grep -qE "^(chore|feat): release v[0-9]+\.[0-9]+\.[0-9]+"; then
            echo "should-run=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "should-run=true" >> $GITHUB_OUTPUT

  update-changelog:
    needs: should-run
    if: needs.should-run.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g conventional-changelog-cli

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Generate Changelog
        run: |
          # Generate full changelog
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet CHANGELOG.md || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'docs: update CHANGELOG.md [skip changelog]'
          title: '📝 Update CHANGELOG.md'
          body: |
            This PR automatically updates the CHANGELOG.md file based on recent commits.
            
            Changes:
            - Regenerates full changelog using conventional commits
            - Updates formatting and structure
            
            This is an automated PR created by the changelog workflow.
          branch: update-changelog
          base: main
          labels: |
            documentation
            automated pr
          delete-branch: true
