name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 15

    env:
      FORCE_COLOR: 1
      NODE_ENV: test
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm audit

      - name: Run tests
        id: test
        continue-on-error: true
        run: |
          npm test || echo "Tests failed but continuing with release"
          echo "Test exit status: $?"

      - name: Report test status
        run: |
          if [ "${{ steps.test.outcome }}" == "failure" ]; then
            echo "::warning::Tests failed but continuing with release"
          fi

      - name: Generate Changelog
        run: |
          npm run changelog
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_ENV
          cat CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build action
        run: npm run prepare

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            LICENSE
            README.md
            CHANGELOG.md
          body: |
            ${{ env.CHANGELOG_CONTENT }}
            
            ${{ steps.test.outcome == 'failure' && '⚠️ Note: This release was created with failing tests' || '✅ All tests passed' }}
